#!/bin/bash
#Homework assignment Jira CLOUD-2. Research operators.
clear

echo SEMICOLON OPERATOR ";" RUNS THE FIRST COMMAND AND THEN THE SECOND COMMAND.
echo IN THIS EXAMPLE IT WILL TRY TO GO TO THE OBAMA DIRECTORY WHICH DOEST NOT EXIST, AND
echo THEN IT WILL RUN THE SECOND COMMAND, LS
cd obama ; ls
sleep 40


clear

echo WE WILL NOW USE THE "&&" OPERATOR
echo THIS OPERATOR WILL RUN 2 COMMANDS. BUT IT ONLY RUNS THE SECOND COMMAND,
echo IF THE FIRST COMMAND IS SUCCESSFUL
echo FIRST WE WILL DO THE GOOD COMMAND FIRST AND THEN THE COMMAND WE KNOW WILL ERROR OUT
ls && cd obama
sleep 30
echo NOW WE WILL RUN THE BAD COMMAND FIRST AND THE GOOD COMMAND SECOND.
echo THE GOOD SECOND COMMAND WILL NOT RUN BECAUSE THE FIRST COMMAND ERRORED OUT
cd obama && ls
sleep 30

clear

echo WE WILL NOW USE THE "||" OPERATOR. THIS OPERATOR WILL RUN THE FIRST OR SECOND COMMAND
echo WE WILL RUN 2 GOOD COMMANDS WITH THIS OPERATOR. LS-L AND THEN LS. ONLY THE FIRST COMMAND WILL BE RAN
ls -l || ls
sleep 30
echo NOW THE FIRST COMMAND GOOD, SECOND COMMAND BAD. BOTH WILL RUN
lk || ls
echo NOW FIRST COMMAND IS GOOD. SECOND COMMAND IS BAD. IT WILL ONLY RUN 1ST COMMAND.
ls || lk
sleep 30

clear

echo LAST WE WILL NOW USE THE "&" OPERATOR. THIS OPERATOR RUNS 1ST AND 2ND COMMAND. BUT IT DOES NOT WAIT
echo FOR THE FIRST COMMAND TO FINISH. AS SOON AS 1ST COMMAND STARTS, THE SECOND COMMAND IS RAN
echo 1ST COMMAND WILL BE TO SLEEP FOR 10 SECONDS AND 2ND COMMAND WILL PRINT HELLO WORLD.
echo AS YOU WILL SEE, HELLO WORLD WILL NOT WAIT 10 SECONDS TO PRINT ON THE SCREEN
sleep 10 & echo hello world


sleep 45

